package com.virohtus.dht.transport.connection;

/**
 * Handles events generated by a Connection
 */
public interface ConnectionDelegate {
    void dataReceived(byte[] data);
    void receiverStopped();
}
